services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: my_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
